### ISSUE TITLE
Unknow protocol

### ISSUE THREAD

**Issue by bu2zhouzhu** [binux/yaaw#103]
终端启动aria2c，chrome打开file:///path/to/binux-yaaw/index.html，页面上显示Unknow protocol。同时刻打开YAAW for chrome插件，没有问题，可以读取到aria2的版本、Base Dir等信息

**Comment by bu2zhouzhu** [comment]
从[这里](https://github.com/binux/yaaw/zipball/master)下载下来的binux-yaaw.zip解压后启动的index.html页面Settings中的JSON-RPC Path的初始值是file://localhost:6800/jsonrpc。把file改为http就好了。最终为http://localhost:6800/jsonrpc

**Comment by binux** [comment]
作为一个 web 项目，从本地运行是错误的用法，file 的环境和 http 有些许不同。不建议直接双击打开，请使用静态文件服务器托管访问。
