### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by txtsd** [binux/yaaw#117]
`Failed to load http://localhost:6800/jsonrpc?tm=1506436909913: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.`
Chrome and FIrefox devtools show this message. The page itself says `Error: Internal server error`

Tried in Chrome 62 and Firefox 58a.

nginx config is:
```
location /yaaw/ {
    alias        /usr/share/webapps/yaaw/;
}
```    
JSON-RPC PATH is setup correctly with token. aria2c config file for daemon is set and running.

**Comment by binux** [comment]
enable `--rpc-allow-origin-all` for aria2

**Comment by txtsd** [comment]
Thanks. That fixed it. Also it worked fine with ws:// when http:// was failing.
