### ISSUE TITLE
如何从多个地址下载同一个文件？

### ISSUE THREAD

**Issue by baoang** [binux/yaaw#124]
今天终于成功的试着下载了文件，于是我想把前几天的一个软件下下来试试。

官方文档说明如下的操作命令，分别是从HTTP和FTP，以及从两个HTTP下载。

    $ aria2c "http://host1/file.zip" "ftp://host2/file.zip"

或者

    $ aria2c "http://host/file.zip" "http://mirror/file.zip"

但是，如何在网页界面做到这一点呢？也就是在`Add task`那个窗口里面？分行填入不同的地址吗？

**Comment by binux** [comment]
yaaw 不支持同一个文件多个来源。多行URL视作多个文件。
