### ISSUE TITLE
aria2c.com 是官方的吗？

### ISSUE THREAD

**Issue by FranklinYu** [binux/yaaw#155]
http://aria2c.com 这个网站似乎用的是 yaaw，请问是不是官方的部署？和 https://binux.github.io/yaaw/demo/ 是一样的吗？

**Comment by holll** [comment]
来自https://github.com/aa65535/yaaw-zh-hans

**Comment by FranklinYu** [comment]
原來在其「設置」中有寫。抱歉打擾！
