### ISSUE TITLE
Active Tasks don't update if any task is expanded

### ISSUE THREAD

**Issue by tdack** [binux/yaaw#66]
If any task (Active or Other) is expanded to show the status, files or options then the updating of the details (download speed, ETA, percentage, amount downloaded) on the Active Tasks stops.

When the expanded task is collapsed the updating resumes.

The overall download/upload indicator in the top right corner continues to be updated when a task is expanded.

**Comment by binux** [comment]
It's designed like that. YAAW is not using data binding frameworks like AngularJS. View updating is handwritten, and it's updating the hold element not only the value of speed, ETA ... 
Therefore when the task is expanded, updating will break your unsaved choices of files or options.

**Comment by tdack** [comment]
OK.  It's not that big of a deal for me.

Thanks for replying.
