### ISSUE TITLE
[Feature-Request] 下载完成后弹出通知

### ISSUE THREAD

**Issue by skyline75489** [binux/yaaw#70]

**Comment by binux** [comment]
非插件不可能实现吧。

That's impossible except extensions.

**Comment by skyline75489** [comment]
像 Web QQ 的话是可以弹出系统通知的，应该不算不可能实现吧

**Comment by binux** [comment]
那我看看吧

**Comment by Haocen** [comment]
好像只有 Chrome 提供了相关接口，其他浏览器则不行。

**Comment by skyline75489** [comment]
我在 Firefox 里用 WebQQ 也能弹出通知来，应该都有吧

**Comment by Haocen** [comment]
的确。是我没弄清楚。
这里有一个例子，据说是在 Opera Safari Firefox 和 Chrome 上通用的：
http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example

**Comment by binux** [comment]
I've added this feature 9da9858cc0fb3f52ebae4b878622220dadf8ebc5.

**Comment by skyline75489** [comment]
Awesome! Thanks!

**Comment by skyline75489** [comment]
Awesome! Thanks!
