### ISSUE TITLE
无法在https下使用

### ISSUE THREAD

**Issue by maz-1** [binux/yaaw#76]
如果luci开启了https，从luci-app-aria2访问aria2也会用https，就会出错
如果确实不能在https下使用，能不能在检测到https时自动重定向到http？

**Comment by binux** [comment]
YAAW 可以在 https 下使用。
如果你在开启了 https 的环境下用 YAAW，aria2 也要开启 https

**Comment by maz-1** [comment]
"aria2 也要开启 https"是指rpc-certificate和rpc-secure么

**Comment by binux** [comment]
请读 aria2 的 manual

**Comment by maz-1** [comment]
自己用openssl生成了p12密钥对，可以用
