### ISSUE TITLE
可不可以添加chrome的消息提醒功能？

### ISSUE THREAD

**Issue by pcwuyu** [binux/yaaw#77]
下载放在后台的话根本不知道下载进度，是否可以添加下载完成之后显示消息提醒的功能？？万分感谢~

**Comment by tofuliang** [comment]
这个功能有的呀.点一下扳手就可以设置了.
鄙人的汉化版 http://yaaw-cn.coding.io/

**Comment by pcwuyu** [comment]
万分感谢～有源码不？我想学习一下

**Comment by binux** [comment]
你提问的这个地方就是放源码的地方。

**Comment by pcwuyu** [comment]
你的没有消息提醒吧。。。。。

**Comment by pcwuyu** [comment]
之前我用的竟然不是最新版。。。
