### ISSUE TITLE
layout problem

### ISSUE THREAD

**Issue by stangri** [binux/yaaw#92]
![screen shot 2016-05-01 at 21 09 57](https://cloud.githubusercontent.com/assets/4768176/14947027/32da421e-0fe1-11e6-945a-158460518f72.png)

Despite enough width of the browser, the number 20 is not properly placed. I'm not fluent enough in CSS/HTML5 to provide a fix tho. :(

**Comment by stangri** [comment]
Attaching a better screenshot.
![screen shot 2016-05-01 at 21 50 21](https://cloud.githubusercontent.com/assets/4768176/14948972/cb5d243e-0ffa-11e6-977a-f2fcc7df8213.png)

**Comment by binux** [comment]
It looks not very good having longer progress bar...

**Comment by stangri** [comment]
Not sure if this has been ever addressed or not.
