### ISSUE TITLE
不支持Token验证？

### ISSUE THREAD

**Issue by kenvix** [binux/yaaw#94]
按照文档设置JSON-RPC 链接后提示 **Error: Unauthorized**
我设置的JSON-RPC链接：
`http://token:AAAAAAAAAAAAAAAAAAA@192.168.1.2:6800/jsonrpc`
ARIA2信息：
```
aria2 version 1.19.0
Copyright (C) 2006, 2015 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **
Enabled Features: BitTorrent, GZip, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.8 libxml2/2.9.1
Compiler: gcc 4.9.2
  built by   armv7l-unknown-linux-gnueabihf
  on         Apr  9 2016 22:23:48
System: Linux 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l

Report bugs to https://github.com/tatsuhiro-t/aria2/issues
Visit http://aria2.sourceforge.net/
```
使用aria2 webui可以正常链接

**Comment by binux** [comment]
你用的是什么版本（哪里的） yaaw？
发出的请求是怎样的

**Comment by kenvix** [comment]
从本仓库下载的最新版本。
![20160508223652](https://cloud.githubusercontent.com/assets/4546175/15098335/a06ec21e-156d-11e6-85b4-336a3eaab58f.jpg)

**Comment by binux** [comment]
你的请求使用的是 basic auth 认证，看起来 yaaw 并没有将你设置的参数识别为 token 认证。

你确认下是否有拼写错误

`url.match(/^(?:(?![^:@]+:[^:@\/]*@)[^:\/?#.]+:)?(?:\/\/)?(?:([^:@]*(?::[^:@]*)?)?@)?/)[1]`

返回的结果是否以 `token:` 开头。

在 http://binux.github.io/yaaw/demo/ 上试试是否有一样的问题

**Comment by kenvix** [comment]
![20160514225726](https://cloud.githubusercontent.com/assets/4546175/15269107/55a3ec3c-1a27-11e6-8189-32a825d703b5.jpg)
在 http://binux.github.io/yaaw/demo/ 同样能识别但是也提示**Error: Unauthorized**

**Comment by kenvix** [comment]
奇怪，在 http://binux.github.io/yaaw/demo/ 可以正常使用了

**Comment by binux** [comment]
YAAW 并没有官方中文版，第一张截图显示的版本可能并不支持 token 认证

**Comment by kenvix** [comment]
感谢作者耐心答复。
我找到原因了，是浏览器缓存导致的（之前用过非官方的中文版）
