### ISSUE TITLE
The task list can't MoveEnd on Aria2 Web Frontend

### ISSUE THREAD

**Issue by tsingui** [binux/yaaw#95]
Hi
I found a bug  on  Aria2 Web Frontend.
The pause task list can't move(the front task) to in the end on Aria2 Web Frontend.
The detailed information ( http://pan.baidu.com/s/1i49XhyP)

**Comment by heraclitusq** [comment]
I've encountered the same issue. 'move down' works fine but 'move end' doesn't work. my aria2 version is 1.18.8 (debian)
